import {
  ForkKnife,
  CoatHanger,
  TShirt,
  Scissors,
  Wine,
  Pill,
  PhoneCall,
  LightbulbFilament,
  Train,
  NotePencil,
  House,
  NavigationArrow,
} from "phosphor-react";

export const categoryDate = [
  {
    id: 1,
    name: "食費",
    image: `${process.env.PUBLIC_URL}/pencil.png`,
    icon: "ph ph-fork-knife",
    categoryId: 7,
  },
  {
    id: 2,
    name: "日用品",
    image: `${process.env.PUBLIC_URL}/pencil.png`,
    icon: "ph ph-coat-hanger",
    categoryId: 3,
  },
  {
    id: 3,
    name: "衣服",
    image: `${process.env.PUBLIC_URL}/pencil.png`,
    icon: "ph ph-t-shirt",
    categoryId: 4,
  },
  {
    id: 4,
    name: "美容",
    image: `${process.env.PUBLIC_URL}/pencil.png`,
    icon: "ph ph-scissors",
    categoryId: 1,
  },
  {
    id: 5,
    name: "交際費",
    image: `${process.env.PUBLIC_URL}/pencil.png`,
    icon: "ph ph-wine",
    categoryId: 12,
  },
  {
    id: 6,
    name: "医療費",
    image: `${process.env.PUBLIC_URL}/pencil.png`,
    icon: "ph ph-wine",
    categoryId: 5,
  },
  {
    id: 7,
    name: "通信費",
    image: `${process.env.PUBLIC_URL}/pencil.png`,
    icon: "ph ph-phone-call",
    categoryId: 11,
  },
  {
    id: 8,
    name: "光熱費",
    image: `${process.env.PUBLIC_URL}/pencil.png`,
    icon: "ph ph-lightbulb-filament",
    categoryId: 2,
  },
  {
    id: 9,
    name: "交通費",
    image: `${process.env.PUBLIC_URL}/pencil.png`,
    icon: "ph ph-train",
    categoryId: 8,
  },
  {
    id: 10,
    name: "教育費",
    image: `${process.env.PUBLIC_URL}/pencil.png`,
    icon: "ph ph-note-pencil",
    categoryId: 9,
  },
  {
    id: 11,
    name: "住居費",
    image: `${process.env.PUBLIC_URL}/pencil.png`,
    icon: "ph ph-house",
    categoryId: 10,
  },
  {
    id: 12,
    name: "その他",
    image: `${process.env.PUBLIC_URL}/pencil.png`,
    icon: "ph ph-navigation-arrow",
    categoryId: 6,
  },
];

export const categoryNameList = [
  "食費",
  "日用品",
  "衣服",
  "美容",
  "交際費",
  "医療費",
  "通信費",
  "光熱費",
  "交通費",
  "教育費",
  "住居費",
  "その他",
];

export const categoryIdList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
